// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ControlService(arg1:string,arg2:string):Promise<void>;

export function DisableAutorun(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportCurrentBundle():Promise<string>;

export function GetInventory():Promise<main.InventorySnapshot>;

export function GetProcessDetail(arg1:number):Promise<main.ProcessDetail>;

export function GetSnapshot():Promise<main.SystemSnapshot>;

export function GetUISettings():Promise<main.UISettings>;

export function ImportBundleDialog():Promise<main.AnalysisBundle>;

export function KillProcess(arg1:number):Promise<void>;

export function SetWindowMode(arg1:string):Promise<main.UISettings>;

export function UpdateServiceStartType(arg1:string,arg2:string):Promise<void>;
