// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ControlService(arg1, arg2) {
  return window['go']['main']['App']['ControlService'](arg1, arg2);
}

export function DisableAutorun(arg1, arg2, arg3) {
  return window['go']['main']['App']['DisableAutorun'](arg1, arg2, arg3);
}

export function ExportCurrentBundle() {
  return window['go']['main']['App']['ExportCurrentBundle']();
}

export function GetInventory() {
  return window['go']['main']['App']['GetInventory']();
}

export function GetProcessDetail(arg1) {
  return window['go']['main']['App']['GetProcessDetail'](arg1);
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function GetUISettings() {
  return window['go']['main']['App']['GetUISettings']();
}

export function ImportBundleDialog() {
  return window['go']['main']['App']['ImportBundleDialog']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function SetWindowMode(arg1) {
  return window['go']['main']['App']['SetWindowMode'](arg1);
}

export function UpdateServiceStartType(arg1, arg2) {
  return window['go']['main']['App']['UpdateServiceStartType'](arg1, arg2);
}
